# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projectes\WSE5784\frontHand\stock_portfolio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(917, 768)
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.mainLayout.addWidget(self.verticalScrollBar)
        self.infoFrame = QtWidgets.QFrame(self.centralwidget)
        self.infoFrame.setObjectName("infoFrame")
        self.portfolioList = QtWidgets.QListView(self.infoFrame)
        self.portfolioList.setGeometry(QtCore.QRect(10, 0, 431, 361))
        self.portfolioList.setObjectName("portfolioList")
        self.listFrame = QtWidgets.QFrame(self.infoFrame)
        self.listFrame.setGeometry(QtCore.QRect(450, 0, 435, 707))
        self.listFrame.setObjectName("listFrame")
        self.vivoList = QtWidgets.QListView(self.listFrame)
        self.vivoList.setGeometry(QtCore.QRect(0, 0, 421, 701))
        self.vivoList.setObjectName("vivoList")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.infoFrame)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 380, 114, 21))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.infoFrame)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.mainLayout.addWidget(self.infoFrame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setStock_portfolio(_translate("Dialog", "Share Portfolio Manager"))
        self.portfolioList.setToolTip(_translate("Dialog", "Portfolio"))
        self.vivoList.setToolTip(_translate("Dialog", "Vivo Stock List"))
